.TH "PETRIS" "6" "February 22, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
petris \- Petris is Peter's Tetris(TM)
.SH SYNOPSIS
.B petris
.RI [ size ]
.SH DESCRIPTION
This manual page documents briefly the
.B petris
command.
.PP
\fBpetris\fP is a clone of Tetris(TM) for the command line. It supports colour and
a highscore file (see /usr/share/doc/petris/README for details).
.SH OPTIONS
This program does not have any normal command line options.

The only option available is:
.TP
.B [WIDTHxHEIGHT]
Sets the size of the terminal window.
\fBExample:\fP petris 12x25
.SH AUTHOR
This manual page was written by Andree Leidenfrost <aleidenf@bigpond.net.au>,
for the Debian project (but may be used by others).
